apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:1lqlGFC1W9YdpbbUKX4lwAg/jhQur2HWYrA0xGKpVQFvFmV1jICQPTxCpO+gPQOlzSRXWDm3YXEOg4Jg,iv:gv0HFx6KNh0e7cSiDJ6PDktY9tcraBnF+kCPIF9uOXA=,tag:y7PSH81nsDOk+zPUAJN+Cw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k8xaut2yz4ttudhtwxk0jf8ckrav2rugjup5vyqu3tyzp2lxhgxq93u2mf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTmo5YlRtQ0FEeFNNd3lD
            M044dkNJZVd1UmVEeXkyVHVyeHR3US81QkI0CkV4YVd3MHBwY3pyc1p1ZUZZa2My
            VTIxODcvQlgrMHNieE5mSEhtRk1naTgKLS0tIDV0ckpkb0ZjSWNSTWtMN0lUTlpM
            ZFBoWmRWT3ZwMm53L1Y3MWNGejlrSG8KN7HAs9VLxhuUdcHe9JDReOO+8rMsM6HN
            yVOJHp9b6u40W6vGNg5TreRohr1dIIiiroG1ewkYwAfXCD8rbFuK1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-27T07:15:23Z"
    mac: ENC[AES256_GCM,data:5oaa3TMtOpkRune1SqkfpgXi5czxJkbtJcd7QLuzeoRhpMYNAFGf4Z9aLO2ss0/t9Ebhm/PUNiFlXgZUESL9tCyxqjDN4tOVyncCb9j1FqVlXZDTriTWZfbKBGQDEs9r0/2JXkGICCA2Sw6FpXE84qWA/0d8/UiTnz5FeexTGYY=,iv:mRheobtn5OcZXLVmR++xDxNJXeJfUEgXkuj3smJv8w4=,tag:p7EipYDWklc6gPXHn55zpA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
