apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:faxaZRzI64Nt+zbb700NIOKPgkLolR05Zyjxo7WZRAwjjctNmXs++38CZjorWIVUP/cI3peMfZfgOkMn,iv:ee028TvwcXP0dcrZXZs1jGO7KWiEdViNrrVbQDbyZC4=,tag:YD+Ri5P7UKX/ph774oH5FQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k8xaut2yz4ttudhtwxk0jf8ckrav2rugjup5vyqu3tyzp2lxhgxq93u2mf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZXVWSndEK21TNWkwRTFN
            Vm1YY1EveTJmZ1lETTVOenRzdlIrMEllNVJBCkJBMEQwQmRvUXIzd1lrZlo3ZHJa
            dDI3QzhoWTRBU1A3cEd6MjFBRnpCVmsKLS0tIEk1YmdmcUtYbFJvYjZ2UTdqaUE1
            dS95ZVVMTDFld3UyMEszUHhDZUFrdWMKUEKHQEg7Ixljdv64VnE89ebgfxsjHQlA
            u4307KDyvOttHy57MnMQxPlgIbrzW5W5cq9+Ml13kXPVyUq9qCW4nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-27T08:15:24Z"
    mac: ENC[AES256_GCM,data:fPtXikZtYpzMDng1+jWP7ej/egqDrAM4XOWlsZ4nIY7x0tpyamzfsI8uqKTqe53ymH9Rz9L0S+KSTGOEbGvo0Lcat7TI9UnpxHWN9GnnQxB/DGAkUvdsfaSOTU1DpE+R2311RuhV1tai2wxZSG9r5zgvy3dTec7q/eHhg3HJcAI=,iv:aYWN3EOFI7I8z4h42qXWldxzOmJudXrNUQ75fm/8sNw=,tag:KhkBhfs4squ2cMvnd9DgdQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
