apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:6tae9ONYQLrYHJKzAcMXryN7,iv:zMv4Y3pt3F/F1PotTbeC4cWk/XX6KcG+/StlW+7MbPc=,tag:QSzEhyhn8XWPPRv5vQYSoQ==,type:str]
    api-key: ENC[AES256_GCM,data:IxOJTcXDBEYiSbktxi8N34E19sbh/rX6J0FcvPSRhan0v/XR2Q==,iv:S6kX9BajKx9JY4pQKhPEtegCThfPj2QaN73h9VaWHy8=,tag:t7+oWwCRbd6UBATHqVy7xw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k8xaut2yz4ttudhtwxk0jf8ckrav2rugjup5vyqu3tyzp2lxhgxq93u2mf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSlFuVFYrd2x3WUhwU2pC
            Rm04RWJqZ2NsS2IrUE1QQ3hvNU1rY05tN21rCi9NM3oyT2RNOURORGpVTW1oMDho
            a1lBU1NXV0xHQlh1aXdmNjdnUklVOFUKLS0tIHZIaUd3ckZadkZCRmRDQ2lRMXhx
            c2E2enhENUV1bFBrbS8yTVk3OFQyYnMKcWiBZK1yOcPVXZ05rzQYRuIVIcoUZOOK
            Qb/gpO2/Er7rOzYC5Q+Ua1kaEcVkE+loPKfSCFRlX6gHTsXVDWG48w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-27T08:15:24Z"
    mac: ENC[AES256_GCM,data:9IHU5y3f05NzdLig12aZMiFbaP0E9NV7+rMZRxqJTyI6xkUjMFlr3I1/UaQOsdGOs3jT+bP6w3DKTiZaxRvIOzmKjdBXIilOXuSI73O6fs8EID97JmlWzpal6AjqMo7MzcnAKZ0Hc7pP4DHny5jJ0z9JE0QtyINymMxnnRH47hs=,iv:eC1XgkE+3Mvy93jthzcyz3j6bqxNtuM+q4ThQhkbnvg=,tag:Vtar5YkCR1AWB0SR7cYgaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
