apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:CUozOmtWLGBBV0VWIO0841Ls,iv:Kjd87srqqs6t5h/hB3LPXJwHOTwAUsvqYSlbnaK54A8=,tag:caM97IMKF5QMcBngzINGCg==,type:str]
    api-key: ENC[AES256_GCM,data:gWy7+ya2gRNN31v6ZivZT9xb1bN9yC+PnTQZJHqdjeDX4JVnNg==,iv:h2z6yF125QJEx7B6bAYGiawOM0eLA081E5lNbEecm54=,tag:8Oezj68ZfU7gTTuOQ3TrOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k8xaut2yz4ttudhtwxk0jf8ckrav2rugjup5vyqu3tyzp2lxhgxq93u2mf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZzUvVWhUS1N3Vk9vWW9O
            ejIrdTIxenBjQ1BEZWpYOWMrOWlvWTE2TzN3CmdnaERObml2MHFSMnU5TlRaYmN6
            VDdBWktoRlNVaU90aTZseWpaTFAxQjgKLS0tIFluUjdKVC9SYzFSeFdVaHpXOFY3
            dE5JbSsrWWdwM2RaakIwQXVvZno3VVEKplPuExP8gvDJdX6wSpd0n90Qa9FryTnQ
            MCw7Sz98+jyFDyre18azX6z1YAJ+sWKAjh5K63yK/UIfkOYrgqYKHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-27T07:15:23Z"
    mac: ENC[AES256_GCM,data:fDMKzfZen5uDekfha6ADgFLW48Uk4XKYg8crG4gdsftT26ayCEE9+jTmlRoocEiroaq8izgJgScVOssmEziGGKs7n93JPBC6MIbHBAaZJATZs98wNl0IPD+TNF+crS+398Wk/9goSIOU6uyrfA/esc2dFiw0bUYQwpvbliUHmtE=,iv:0AyIl3eyoUKWx78xfC/J3Ce6ODD/rCIZ7ipsL69o6zM=,tag:KRDCPXcJ6i2yqNuRv1yFXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
